name: Michael Nigosian Architecture
favicon: null
layout_spectrum: 0.8140549894887954
typography_spectrum: 0.24651056481525302
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6595d7'
    - '#ced0c5'
    - '#243721'
    - '#505244'
    - '#ab7962'
  brandStrength: 0.7224061056040227
  lightness: 0.883029782678932
  saturation: 0.1597427383530885
  rhythmicContrast: 0.15689023374579847
purpose: []
