name: Michael Nigosian Architecture
favicon: null
layout_spectrum: 0
typography_spectrum: 0.68865
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#bfaf9e'
    - '#35302c'
    - '#827160'
  brandStrength: 0.5
  lightness: 0.883029782678932
  saturation: 0.1597427383530885
  rhythmicContrast: 0.15689023374579847
purpose: []
